import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Amplify } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import awsExports from '../src/aws-exports';

export default function Home({ signOut, user }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>sportin' around</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Hallo</div>
    </div>
  );
}
